server:
  port: 9080
  servlet:
    context-path: /elastic
spring:
  data:
    elasticsearch:
      cluster-nodes: 192.168.102.31:9300
      cluster-name: es-saas
      repositories:
        enabled: true
